"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.Person = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
var person_js_1 = require(".company/test/person.js");
Object.defineProperty(exports, "Person", { enumerable: true, get: function () { return person_js_1.Person; } });
