name: CI
permissions: read-all

on:
  # For manual tests.
  workflow_dispatch:
  push:
    tags:
      - "*" # new tag version, like `0.8.4` or else
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-ts:
    name: Build TS
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: flatc
      # FIXME: make test script not rely on flatc
      run: cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DFLATBUFFERS_BUILD_TESTS=OFF -DFLATBUFFERS_INSTALL=OFF -DFLATBUFFERS_BUILD_FLATLIB=OFF -DFLATBUFFERS_BUILD_FLATHASH=OFF . && make -j
    - name: deps
      run: yarn
    - name: compile
      run: yarn compile
    - name: test
      working-directory: tests/ts
      run: |
        yarn global add esbuild
        python3 TypeScriptTest.py
    - name: compile
      run: tsc
      working-directory: tests/ts